In [2]:
%pip install chardet

Requirement already satisfied: chardet in c:\python31\python311\lib\site-packages (3.0.4)Note: you may need to restart the kernel to use updated packages.

In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

file_path= r'C:\Users\marie\Downloads\Machine_Learning\indicators.csv'
df = pd.read_csv(file_path, encoding='latin-1')
df.head()

,ent,nom_ent,mun,clave_mun,nom_mun,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,...,pobreza_alim_10,pobreza_cap_90,pobreza_cap_00,pobreza_cap_10,pobreza_patrim_90,pobreza_patrim_00,pobreza_patrim_10,gini_90,gini_00,gini_10
0,1,Aguascalientes,1,1001,Aguascalientes,794304,30.531104,2.264478,28.266627,27.983320,...,11.805700,20.4,12.7,18.474600,43.4,33.7,41.900398,0.473,0.425,0.422628
1,1,Aguascalientes,2,1002,Asientos,48592,67.111172,8.040704,59.070468,22.439389,...,21.993299,39.9,29.0,30.980801,64.2,48.9,59.175800,0.379,0.533,0.343879
2,1,Aguascalientes,3,1003,Calvillo,53104,61.360527,7.241238,54.119289,29.428583,...,19.266800,39.5,33.1,28.259199,63.9,57.9,56.504902,0.414,0.465,0.386781
3,1,Aguascalientes,4,1004,Cosío,14101,52.800458,4.769001,48.031458,27.128568,...,14.303200,35.2,21.0,22.386101,59.7,40.1,51.164501,0.392,0.541,0.344984
4,1,Aguascalientes,5,1005,Jesús María,101379,45.338512,6.084037,39.254475,26.262912,...,15.085100,36.6,22.6,22.139999,60.6,42.2,45.703899,0.391,0.469,0.458083

CLEAN DATASET

In [5]:
df.dtypes
# Para contar valores nulos en cada columna
null_counts = df.isna().sum()
# print(null_counts)

#rellenar valores nulos
df.bfill(inplace=True)
print(null_counts)

ent                  0
nom_ent              0
mun                  0
clave_mun            0
nom_mun              0
                    ..
pobreza_patrim_00    3
pobreza_patrim_10    0
gini_90              2
gini_00              3
gini_10              0
Length: 139, dtype: int64

In [6]:
#Drop first five columns
df.drop(df.columns[0:5], axis=1, inplace=True)
df.head()

,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,vul_ing,npnv,ic_rezedu,ic_asalud,ic_segsoc,...,pobreza_alim_10,pobreza_cap_90,pobreza_cap_00,pobreza_cap_10,pobreza_patrim_90,pobreza_patrim_00,pobreza_patrim_10,gini_90,gini_00,gini_10
0,794304,30.531104,2.264478,28.266627,27.983320,8.419106,33.066469,14.970553,24.034493,41.799885,...,11.805700,20.4,12.7,18.474600,43.4,33.7,41.900398,0.473,0.425,0.422628
1,48592,67.111172,8.040704,59.070468,22.439389,5.557604,4.891835,21.222712,15.514032,78.003570,...,21.993299,39.9,29.0,30.980801,64.2,48.9,59.175800,0.379,0.533,0.343879
2,53104,61.360527,7.241238,54.119289,29.428583,2.921336,6.289554,27.361207,20.812551,80.051980,...,19.266800,39.5,33.1,28.259199,63.9,57.9,56.504902,0.414,0.465,0.386781
3,14101,52.800458,4.769001,48.031458,27.128568,7.709276,12.361698,20.889023,14.071657,65.831374,...,14.303200,35.2,21.0,22.386101,59.7,40.1,51.164501,0.392,0.541,0.344984
4,101379,45.338512,6.084037,39.254475,26.262912,8.279864,20.118712,20.578144,16.567818,52.616992,...,15.085100,36.6,22.6,22.139999,60.6,42.2,45.703899,0.391,0.469,0.458083

In [7]:
# Convert into numerical
df = pd.get_dummies(df, dtype='int64')
df

,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,vul_ing,npnv,ic_rezedu,ic_asalud,ic_segsoc,...,gdo_rezsoc05_Alto,gdo_rezsoc05_Bajo,gdo_rezsoc05_Medio,gdo_rezsoc05_Muy alto,gdo_rezsoc05_Muy bajo,gdo_rezsoc10_Alto,gdo_rezsoc10_Bajo,gdo_rezsoc10_Medio,gdo_rezsoc10_Muy alto,gdo_rezsoc10_Muy bajo
0,794304,30.531104,2.264478,28.266627,27.983320,8.419106,33.066469,14.970553,24.034493,41.799885,...,0,0,0,0,1,0,0,0,0,1
1,48592,67.111172,8.040704,59.070468,22.439389,5.557604,4.891835,21.222712,15.514032,78.003570,...,0,0,0,0,1,0,0,0,0,1
2,53104,61.360527,7.241238,54.119289,29.428583,2.921336,6.289554,27.361207,20.812551,80.051980,...,0,0,0,0,1,0,0,0,0,1
3,14101,52.800458,4.769001,48.031458,27.128568,7.709276,12.361698,20.889023,14.071657,65.831374,...,0,0,0,0,1,0,0,0,0,1
4,101379,45.338512,6.084037,39.254475,26.262912,8.279864,20.118712,20.578144,16.567818,52.616992,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2451,21016,74.848837,12.301183,62.547654,19.229856,3.177689,2.743618,27.350040,36.056322,76.550988,...,0,1,0,0,0,0,1,0,0,0
2452,27385,65.450191,10.203506,55.246687,23.623556,5.007426,5.918827,29.914879,53.313420,74.542926,...,0,0,0,0,1,0,0,0,0,1
2453,117528,29.541959,3.535624,26.006335,16.644262,8.828019,44.985759,11.936088,18.316528,32.666426,...,0,0,0,0,1,0,0,0,0,1
2454,20456,78.374962,14.607016,63.767946,13.750759,4.440331,3.433948,26.649950,11.769479,83.235286,...,0,1,0,0,0,0,0,0,0,1
2455,2772,62.204207,10.102023,52.102184,27.489635,2.308246,7.997912,28.429677,44.800160,76.211864,...,0,1,0,0,0,0,0,0,0,1

In [8]:
N_poverty= df['N_pobreza']
df= df.drop('N_pobreza', axis=1)
df['N_poverty']= N_poverty
df.head()

,pobtot_ajustada,pobreza,pobreza_e,pobreza_m,vul_car,vul_ing,npnv,ic_rezedu,ic_asalud,ic_segsoc,...,gdo_rezsoc05_Bajo,gdo_rezsoc05_Medio,gdo_rezsoc05_Muy alto,gdo_rezsoc05_Muy bajo,gdo_rezsoc10_Alto,gdo_rezsoc10_Bajo,gdo_rezsoc10_Medio,gdo_rezsoc10_Muy alto,gdo_rezsoc10_Muy bajo,N_poverty
0,794304,30.531104,2.264478,28.266627,27.983320,8.419106,33.066469,14.970553,24.034493,41.799885,...,0,0,0,1,0,0,0,0,1,242510
1,48592,67.111172,8.040704,59.070468,22.439389,5.557604,4.891835,21.222712,15.514032,78.003570,...,0,0,0,1,0,0,0,0,1,32611
2,53104,61.360527,7.241238,54.119289,29.428583,2.921336,6.289554,27.361207,20.812551,80.051980,...,0,0,0,1,0,0,0,0,1,32585
3,14101,52.800458,4.769001,48.031458,27.128568,7.709276,12.361698,20.889023,14.071657,65.831374,...,0,0,0,1,0,0,0,0,1,7445
4,101379,45.338512,6.084037,39.254475,26.262912,8.279864,20.118712,20.578144,16.567818,52.616992,...,0,0,0,1,0,0,0,0,1,45964

In [9]:
df.isnull().sum()

pobtot_ajustada          0
pobreza                  0
pobreza_e                0
pobreza_m                0
vul_car                  0
                        ..
gdo_rezsoc10_Bajo        0
gdo_rezsoc10_Medio       0
gdo_rezsoc10_Muy alto    0
gdo_rezsoc10_Muy bajo    0
N_poverty                0
Length: 146, dtype: int64

In [10]:
X= np.asarray(df.values.tolist())
Y= np.asarray(df['N_poverty'].values.tolist())
Y= Y.reshape(-1,1)

#fill nan values x
X= np.nan_to_num(X)

In [11]:
print("The shape of the independent variables is: ", X.shape)
print("The shape of the dependent variable is: ", Y.shape)

The shape of the independent variables is:  (2456, 146)
The shape of the dependent variable is:  (2456, 1)

In [12]:
#Use 80% of the data for training and 20% for testing
X_train= np.array(X[:int(len(X)*0.8)])
Y_train= np.array(Y[:int(len(Y)*0.8)])
X_test= np.array(X[int(len(X)*0.8):]) 
Y_test= np.array(Y[int(len(Y)*0.8):])

X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((1964, 146), (1964, 1), (492, 146), (492, 1))

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Create and fit the regression model
regression_model = LinearRegression()
regression_model.fit(X_train, Y_train)

# Make predictions on the test data
Y_predicttt = regression_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)
print(Y_predicttt.shape)

Mean Squared Error: 8.196389607232808e-15
R-squared: 1.0
(492, 1)

In [14]:
# Standardize the training set
X_train_standardized = (X_train - X_train.mean()) / X_train.std()

# Standardize the test set using mean and std from the training set
X_test_standardized = (X_test - X_train.mean()) / X_train.std()

In [19]:
def error_function(y_actual, y_predicted):
    error = 0
    for i in range(0, len(y_actual)):
        error = error + pow((y_actual[i] - y_predicted[i]), 2)
    return error / (2 * len(y_actual))

def y_predicted(w, x):
    y_prediction = np.zeros(len(x))
    for i in range(0, len(x)):
        for j in range(0, len(w) - 1):  # Exclude the last element in w
            y_pred[i] = y_pred[i] + (w[j] * x[i][j])
        y_pred[i] += w[-1]  # Intercept
    return y_prediction

In [16]:

def gradient_descent(y_actual, y_pred, x):
    grad = np.zeros(x.shape[1])
    for i in range(x.shape[1]):
        for j in range(0, len(y_actual)):
            grad[i] = - (y_actual[j] - y_pred[j]) * x[j][i] + grad[i]
    return grad / len(y_actual)

def weights(x_train, y_train, num_iterations, learning_rate):
    no_of_rows = x_train.shape[0]
    no_of_columns = x_train.shape[1]
    new_x_train = np.ones((no_of_rows, no_of_columns + 1))
    new_x_train[:, 0:no_of_columns] = x_train
    w = np.zeros(no_of_columns)
    w = np.append(w, 1)
    for i in range(0, num_iterations):
        y_pred = y_predicted(w, new_x_train)
        error = error_function(y_train, y_pred)
        print("mean square error: ", error, "after", i, "th iteration")
        MSE_points.append(error)
        grad = gradient_descent(y_train, y_pred, new_x_train)
        w = w - learning_rate * grad
        learning_rate = learning_rate / 1.05  # Learning rate Decay
    return w

In [48]:

def regression_test(x_test, w):
    row = x_test.shape[0]
    column = x_test.shape[1]
    new_x_test = np.ones((row, column + 1))
    new_x_test[:, 0:column] = x_test
    y_pred = y_predicted(w, new_x_test)
    return y_pred

def r_squared(y_actual, y_predicted):
    y_mean = np.mean(y_actual)
    ss_tot = sum((y_actual - y_mean) ** 2)
    ss_res = sum((y_actual - y_predicted) ** 2)
    r2 = 1 - (ss_res / ss_tot)
    return r2

MSE_points = []
num_iterations = 300
learning_rate = 0.1
w = weights(X_train_standardized, Y_train, num_iterations, learning_rate)
Y_pred = regression_test(X_test_standardized, w)
mse = error_function(Y_test, Y_pred)
r2 = r_squared(Y_test, Y_pred)
print("Mean Square Error on Test Set: ", mse)

mean square error:  [1.60025833e+09] after 0 th iteration
mean square error:  [2.59207842e+11] after 1 th iteration
mean square error:  [4.05616241e+13] after 2 th iteration
mean square error:  [5.71278322e+15] after 3 th iteration
mean square error:  [7.23660556e+17] after 4 th iteration
mean square error:  [8.24092892e+19] after 5 th iteration
mean square error:  [8.43256236e+21] after 6 th iteration
mean square error:  [7.74926294e+23] after 7 th iteration
mean square error:  [6.39205357e+25] after 8 th iteration
mean square error:  [4.72984353e+27] after 9 th iteration
mean square error:  [3.13769767e+29] after 10 th iteration
mean square error:  [1.8648686e+31] after 11 th iteration
mean square error:  [9.9232766e+32] after 12 th iteration
mean square error:  [4.72399298e+34] after 13 th iteration
mean square error:  [2.01033036e+36] after 14 th iteration
mean square error:  [7.64124227e+37] after 15 th iteration
mean square error:  [2.59184436e+39] after 16 th iteration
mean square error:  [7.83765449e+40] after 17 th iteration
mean square error:  [2.11081892e+42] after 18 th iteration
mean square error:  [5.05740911e+43] after 19 th iteration
mean square error:  [1.07673412e+45] after 20 th iteration
mean square error:  [2.03444819e+46] after 21 th iteration
mean square error:  [3.4068824e+47] after 22 th iteration
mean square error:  [5.04906436e+48] after 23 th iteration
mean square error:  [6.61197063e+49] after 24 th iteration
mean square error:  [7.63813722e+50] after 25 th iteration
mean square error:  [7.76949302e+51] after 26 th iteration
mean square error:  [6.94535473e+52] after 27 th iteration
mean square error:  [5.44464011e+53] after 28 th iteration
mean square error:  [3.73434038e+54] after 29 th iteration
mean square error:  [2.23530467e+55] after 30 th iteration
mean square error:  [1.16451759e+56] after 31 th iteration
mean square error:  [5.26426655e+56] after 32 th iteration
mean square error:  [2.0581681e+57] after 33 th iteration
mean square error:  [6.93423681e+57] after 34 th iteration
mean square error:  [2.00516023e+58] after 35 th iteration
mean square error:  [4.95448589e+58] after 36 th iteration
mean square error:  [1.04085901e+59] after 37 th iteration
mean square error:  [1.84890436e+59] after 38 th iteration
mean square error:  [2.75959933e+59] after 39 th iteration
mean square error:  [3.43639306e+59] after 40 th iteration
mean square error:  [3.541308e+59] after 41 th iteration
mean square error:  [2.99209366e+59] after 42 th iteration
mean square error:  [2.05034518e+59] after 43 th iteration
mean square error:  [1.12508485e+59] after 44 th iteration
mean square error:  [4.86927746e+58] after 45 th iteration
mean square error:  [1.63194813e+58] after 46 th iteration
mean square error:  [4.14107314e+57] after 47 th iteration
mean square error:  [7.73288252e+56] after 48 th iteration
mean square error:  [1.02419987e+56] after 49 th iteration
mean square error:  [9.15546817e+54] after 50 th iteration
mean square error:  [5.14807389e+53] after 51 th iteration
mean square error:  [1.63509079e+52] after 52 th iteration
mean square error:  [2.43810772e+50] after 53 th iteration
mean square error:  [1.14995215e+48] after 54 th iteration
mean square error:  [3.63857244e+44] after 55 th iteration
mean square error:  [3.42443917e+41] after 56 th iteration
mean square error:  [2.02172815e+39] after 57 th iteration
mean square error:  [2.95006469e+37] after 58 th iteration
mean square error:  [7.80568345e+35] after 59 th iteration
mean square error:  [3.20197335e+34] after 60 th iteration
mean square error:  [1.85220553e+33] after 61 th iteration
mean square error:  [1.41793767e+32] after 62 th iteration
mean square error:  [1.37319465e+31] after 63 th iteration
mean square error:  [1.63091612e+30] after 64 th iteration
mean square error:  [2.35999763e+29] after 65 th iteration
mean square error:  [4.49461322e+28] after 66 th iteration
mean square error:  [1.44899488e+28] after 67 th iteration
mean square error:  [8.92362165e+27] after 68 th iteration
mean square error:  [7.76352858e+27] after 69 th iteration
mean square error:  [7.48246936e+27] after 70 th iteration
mean square error:  [7.39719868e+27] after 71 th iteration
mean square error:  [7.36055616e+27] after 72 th iteration
mean square error:  [7.33762481e+27] after 73 th iteration
mean square error:  [7.31933297e+27] after 74 th iteration
mean square error:  [7.30309927e+27] after 75 th iteration
mean square error:  [7.28810809e+27] after 76 th iteration
mean square error:  [7.27406207e+27] after 77 th iteration
mean square error:  [7.26082808e+27] after 78 th iteration
mean square error:  [7.24832972e+27] after 79 th iteration
mean square error:  [7.23651249e+27] after 80 th iteration

In [17]:
print("R-squared on Test Set: ", r2)
print("Predicted Y values: ", Y_pred)

R-squared on Test Set:  1.0
Predicted Y values:  [[129742.        ]
 [ 89548.        ]
 [ 16998.        ]
 [114178.        ]
 [ 20834.        ]
 [ 52816.        ]
 [ 20653.        ]
 [110167.        ]
 [ 65101.        ]
 [ 53987.        ]
 [ 30510.        ]
 [ 34043.        ]
 [ 41726.        ]
 [  8691.        ]
 [ 18117.        ]
 [108039.        ]
 [  6173.        ]
 [  3337.        ]
 [ 10480.        ]
 [  5476.        ]
 [  4675.        ]
 [ 51960.        ]
 [  1605.        ]
 [  6614.        ]
 [ 29966.        ]
 [ 13456.        ]
 [  3385.        ]
 [  8570.        ]
 [ 19443.        ]
 [ 12738.        ]
 [  4577.        ]
 [ 12388.        ]
 [  2343.        ]
 [ 48392.        ]
 [168468.        ]
 [  3548.        ]
 [  1653.        ]
 [ 12261.        ]
 [  4505.        ]
 [140926.        ]
 [  2361.        ]
 [  9203.        ]
 [  9179.        ]
 [  1794.        ]
 [191029.        ]
 [ 61389.        ]
 [  9843.        ]
 [ 39286.        ]
 [  1524.        ]
 [ 17938.        ]
 [ 75881.        ]
 [ 25935.        ]
 [ 37242.        ]
 [ 79009.        ]
 [  5568.        ]
 [ 11378.        ]
 [  5462.        ]
 [  4962.        ]
 [  5142.        ]
 [ 14947.        ]
 [ 39063.        ]
 [ 26997.        ]
 [ 18641.        ]
 [ 11140.        ]
 [  3429.        ]
 [ 35723.        ]
 [  2945.        ]
 [  9937.        ]
 [ 53277.        ]
 [  9748.        ]
 [ 18474.        ]
 [  3322.        ]
 [  9357.        ]
 [ 21436.        ]
 [ 10400.        ]
 [  6672.        ]
 [ 11065.        ]
 [  2501.        ]
 [ 16522.        ]
 [  9182.        ]
 [ 61369.        ]
 [  9991.        ]
 [  7426.        ]
 [ 13223.        ]
 [  5655.        ]
 [ 12965.        ]
 [ 14727.        ]
 [  7350.        ]
 [ 25883.        ]
 [ 33982.        ]
 [  3498.        ]
 [  5061.        ]
 [  8616.        ]
 [ 10396.        ]
 [ 15779.        ]
 [  6052.        ]
 [ 11484.        ]
 [  6283.        ]
 [ 14663.        ]
 [ 19721.        ]
 [  5220.        ]
 [  4237.        ]
 [  2450.        ]
 [ 13160.        ]
 [  2797.        ]
 [  7347.        ]
 [  1343.        ]
 [  4585.        ]
 [  4715.        ]
 [  2171.        ]
 [  1407.        ]
 [  4106.        ]
 [  2384.        ]
 [  3552.        ]
 [  4678.        ]
 [  3633.        ]
 [  5242.        ]
 [  2344.        ]
 [ 64975.        ]
 [ 23877.        ]
 [  2962.        ]
 [ 13997.        ]
 [  4981.        ]
 [  7413.        ]
 [ 18137.        ]
 [ 46205.        ]
 [ 28048.        ]
 [  4877.        ]
 [ 10005.        ]
 [ 25109.        ]
 [ 22175.        ]
 [  8091.        ]
 [  2829.        ]
 [  1396.        ]
 [  4596.        ]
 [  9469.        ]
 [ 15191.        ]
 [ 15216.        ]
 [ 39321.        ]
 [ 12848.        ]
 [ 21709.        ]
 [  8650.        ]
 [ 15619.        ]
 [ 45859.        ]
 [ 10836.        ]
 [ 16451.        ]
 [ 13140.        ]
 [ 29384.        ]
 [ 18205.        ]
 [ 10955.        ]
 [  9212.        ]
 [  8022.        ]
 [  7615.        ]
 [ 38627.        ]
 [108100.        ]
 [ 21654.        ]
 [  1614.        ]
 [  4311.        ]
 [ 16969.        ]
 [ 63796.        ]
 [ 24145.        ]
 [ 13511.        ]
 [ 45656.        ]
 [ 54740.        ]
 [ 12565.        ]
 [ 12629.        ]
 [ 17784.        ]
 [  6567.        ]
 [ 14521.        ]
 [  8050.        ]
 [  8755.        ]
 [  5386.        ]
 [ 10849.        ]
 [ 39863.        ]
 [  9456.        ]
 [ 12818.        ]
 [ 58657.        ]
 [ 14797.        ]
 [ 11697.        ]
 [  3449.        ]
 [ 23507.        ]
 [ 21306.        ]
 [ 14369.        ]
 [ 22497.        ]
 [ 15195.        ]
 [ 16560.        ]
 [ 35001.        ]
 [ 16452.        ]
 [ 30873.        ]
 [  3619.        ]
 [ 13030.        ]
 [ 10472.        ]
 [ 28136.        ]
 [ 10899.        ]
 [  9955.        ]
 [ 18718.        ]
 [  9334.        ]
 [  8765.        ]
 [ 45756.        ]
 [  3937.        ]
 [ 27356.        ]
 [ 37434.        ]
 [177918.        ]
 [  4405.        ]
 [ 23606.        ]
 [  5793.        ]
 [ 20779.        ]
 [ 24839.        ]
 [  8620.        ]
 [ 28305.        ]
 [ 11799.        ]
 [  1272.        ]
 [  9889.        ]
 [  2388.        ]
 [ 12832.        ]
 [ 14452.        ]
 [ 23352.        ]
 [ 46834.        ]
 [ 10961.        ]
 [ 16198.        ]
 [ 27058.        ]
 [  3967.        ]
 [  2675.        ]
 [ 74506.        ]
 [ 50603.        ]
 [  9007.        ]
 [ 11663.        ]
 [ 13619.        ]
 [  3346.        ]
 [  7211.        ]
 [ 18862.        ]
 [  8981.        ]
 [ 13627.        ]
 [ 21596.        ]
 [  2748.        ]
 [ 11512.        ]
 [ 20274.        ]
 [ 15946.        ]
 [ 57531.        ]
 [111408.        ]
 [ 18953.        ]
 [ 19301.        ]
 [ 18690.        ]
 [ 43690.        ]
 [ 13735.        ]
 [ 34336.        ]
 [ 70759.        ]
 [ 15314.        ]
 [ 34776.        ]
 [ 11294.        ]
 [ 15616.        ]
 [  4469.        ]
 [  4727.        ]
 [ 13202.        ]
 [  2855.        ]
 [  2251.        ]
 [108605.        ]
 [ 28336.        ]
 [ 41603.        ]
 [ 26502.        ]
 [  6589.        ]
 [  3118.        ]
 [ 20549.        ]
 [ 18697.        ]
 [ 29441.        ]
 [ 10242.        ]
 [ 20174.        ]
 [  8918.        ]
 [  4299.        ]
 [ 11553.        ]
 [ 78920.        ]
 [  5085.        ]
 [ 16004.        ]
 [ 19671.        ]
 [ 18763.        ]
 [ 87352.        ]
 [ 27362.        ]
 [  5948.        ]
 [  4195.        ]
 [ 10779.        ]
 [  7882.        ]
 [  8228.        ]
 [ 12595.        ]
 [ 12393.        ]
 [ 18219.        ]
 [  8179.        ]
 [  3963.        ]
 [ 18629.        ]
 [ 39781.        ]
 [ 47136.        ]
 [ 70109.        ]
 [  3018.        ]
 [  9340.        ]
 [  6943.        ]
 [  3230.        ]
 [  9131.        ]
 [ 23250.        ]
 [ 10050.        ]
 [ 41953.        ]
 [  5472.        ]
 [  3956.        ]
 [  4133.        ]
 [  5220.        ]
 [ 13862.        ]
 [ 76397.        ]
 [  1525.        ]
 [ 11481.        ]
 [ 12661.        ]
 [168586.        ]
 [ 10942.        ]
 [  4378.        ]
 [ 10638.        ]
 [  8472.        ]
 [  6623.        ]
 [ 10625.        ]
 [ 11064.        ]
 [ 28894.        ]
 [ 12545.        ]
 [ 12480.        ]
 [ 22924.        ]
 [ 12549.        ]
 [ 10543.        ]
 [ 27864.        ]
 [ 14075.        ]
 [ 12526.        ]
 [ 25230.        ]
 [ 19631.        ]
 [ 12260.        ]
 [  4285.        ]
 [ 10157.        ]
 [  4462.        ]
 [  3517.        ]
 [   892.        ]
 [  5095.        ]
 [  3581.        ]
 [  2771.        ]
 [  3708.        ]
 [  1316.        ]
 [  3466.        ]
 [  1996.        ]
 [  4649.        ]
 [   713.        ]
 [  4051.        ]
 [  1476.        ]
 [  2215.        ]
 [  1799.        ]
 [ 17328.        ]
 [  2883.        ]
 [  4917.        ]
 [  2439.        ]
 [  3935.        ]
 [  2251.        ]
 [  3002.        ]
 [  1974.        ]
 [  5118.        ]
 [  1563.        ]
 [  3507.        ]
 [  2410.        ]
 [  1824.        ]
 [  9757.        ]
 [ 11987.        ]
 [  5178.        ]
 [  3891.        ]
 [  4818.        ]
 [  4557.        ]
 [ 21125.        ]
 [  2434.        ]
 [ 16014.        ]
 [ 39768.        ]
 [  4627.        ]
 [  1367.        ]
 [  5539.        ]
 [  1001.        ]
 [  2213.        ]
 [  3376.        ]
 [ 13230.        ]
 [  2464.        ]
 [263837.00000001]
 [  1058.        ]
 [ 19172.        ]
 [  8038.        ]
 [  1118.        ]
 [  4690.        ]
 [ 16463.        ]
 [  3895.        ]
 [ 14479.        ]
 [ 24754.        ]
 [   346.        ]
 [  1576.        ]
 [  3435.        ]
 [  3570.        ]
 [   799.        ]
 [   836.        ]
 [  2512.        ]
 [  8590.        ]
 [  1745.        ]
 [  4861.        ]
 [  2617.        ]
 [   977.        ]
 [   882.        ]
 [  2340.        ]
 [  2407.        ]
 [  5364.        ]
 [ 11003.        ]
 [  1789.        ]
 [  2437.        ]
 [ 23632.        ]
 [  8361.        ]
 [  1991.        ]
 [  1875.        ]
 [   896.        ]
 [  5159.        ]
 [  8678.        ]
 [  1065.        ]
 [  3487.        ]
 [   989.        ]
 [ 23421.        ]
 [  5169.        ]
 [  7019.        ]
 [  4093.        ]
 [  9762.        ]
 [  2464.        ]
 [  3506.        ]
 [ 46715.        ]
 [  2199.        ]
 [  8955.        ]
 [  2552.        ]
 [  2245.        ]
 [ 31635.        ]
 [ 47138.        ]
 [  2329.        ]
 [  8700.        ]
 [  1858.        ]
 [  1011.        ]
 [  2184.        ]
 [  3546.        ]
 [  1744.        ]
 [  3657.        ]
 [ 26349.        ]
 [  6081.        ]
 [  5619.        ]
 [  6991.        ]
 [  7404.        ]
 [118352.        ]
 [  1690.        ]
 [  7488.        ]
 [  4269.        ]
 [ 19139.        ]
 [  1122.        ]
 [ 20407.        ]
 [ 50935.        ]
 [  2239.        ]
 [ 11791.        ]
 [ 31136.        ]
 [  5560.        ]
 [ 15929.        ]
 [  2471.        ]
 [ 31524.        ]
 [  6921.        ]
 [ 20746.        ]
 [  2499.        ]
 [  1130.        ]
 [ 19922.        ]
 [  1377.        ]
 [  4476.        ]
 [  5186.        ]
 [  1192.        ]
 [ 17752.        ]
 [ 15855.        ]
 [ 31497.        ]
 [ 16684.        ]
 [ 58628.        ]
 [ 38209.        ]
 [ 17759.        ]
 [  2796.        ]
 [ 38423.        ]
 [   805.        ]
 [ 10159.        ]
 [  4432.        ]
 [  5015.        ]
 [  2739.        ]
 [ 17449.        ]
 [ 23400.        ]
 [  8275.        ]
 [ 31252.        ]
 [ 13328.        ]
 [  7924.        ]
 [ 15730.        ]
 [ 17924.        ]
 [ 34720.        ]
 [ 16032.        ]
 [  1724.00000201]]

In [22]:
#Create a dataframe with Y, Y_test, 
import pandas as pd
y_data = pd.DataFrame({'Actual': Y_test.flatten(), 'Predicted': Y_pred.flatten(), 'Scikit': Y_predicttt.flatten()})
y_data.head()

   Actual  Predicted    Scikit
0  129742   129742.0  129742.0
1   89548    89548.0   89548.0
2   16998    16998.0   16998.0
3  114178   114178.0  114178.0
4   20834    20834.0   20834.0